[[roles]]
    name = "consul"
    disk = 20000
    memory = 1024
    ostype = "Linux_64"
    iso = "ipxe.iso"
    controllers = ["ide", "sata"]
    interfaces = ["intnet"]
    boot = ["dvd", "disk", "none", "none" ]
    [[roles.hosts]]
        name = "consul-server01.infra.local"
        port = []
        mac = "080027AB1001"
    [[roles.hosts]]
        name = "consul-server02.infra.local"
        port = []
        mac = "080027AB1002"
    [[roles.hosts]]
        name = "consul-server03.infra.local"
        port = []
        mac = "080027AB1003"

[[roles]]
    name = "producer"
    disk = 100000
    memory = 8192
    ostype = "Linux_64"
    iso = "ipxe.iso"
    controllers = ["ide", "sata"]
    interfaces = ["intnet"]
    boot = ["dvd", "disk", "none", "none" ]
    [[roles.hosts]]
        name = "producer01.infra.local"
        port = []
        mac = "080027AB1010"
    [[roles.hosts]]
        name = "producer02.infra.local"
        port = []
        mac = "080027AB1011"
